[project]
name = "spanish-live-output"
version = "0.1.0"
description = "Real-time Spanish speech-to-text transcription using Faster-Whisper"
requires-python = ">=3.13"
dependencies = [
    "faster-whisper>=1.0.0",
    "sounddevice>=0.4.0",
    "numpy>=1.24.0"
]
